version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - user_management_service
      - game_engine_service
      - redis
      - service_discovery

  service_discovery:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - ./data/mongo:/data/db

  gamesdb:
    image: mongo:latest
    container_name: gamesdb
    ports:
      - "27018:27017"
    volumes:
      - ./data/gamesdb:/data/db

  user_management_service:
    build: ./user_management_service
    ports:
      - "5002" 
    expose:
      - "5002"
    depends_on:
      - mongodb
      - service_discovery
    environment:
      MONGO_URL: mongodb://mongodb:27017
    command: sh -c "node registerService.js & gunicorn -w 4 --threads 2 -b 0.0.0.0:5002 app:app"

  game_engine_service:
    build: ./game_engine_service
    ports:
      - "5003:5003"
    expose:
      - "5003"
    depends_on:
      - gamesdb
      - service_discovery
    environment:
      MONGO_URL: mongodb://gamesdb:27017
    command: sh -c "node registerService.js & gunicorn -k eventlet --timeout 60 -w 5 -b 0.0.0.0:5003 app:app"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  mongo_data: {}
  gamesdb_data: {}