version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - service_discovery

  service_discovery:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  gamesdb:
    image: mongo:latest
    container_name: gamesdb
    ports:
      - "27018:27017"
    volumes:
      - gamesdb_data:/data/db

  user_management_service_1:
    container_name: user_management_service_1
    build: ./user_management_service
    expose:
      - "5002"
    depends_on:
      - mongodb
      - service_discovery
    environment:
      MONGO_URL: mongodb://mongodb:27017
      SERVICE_NAME: user_management_service
      SERVICE_ADDRESS: user_management_service_1
      PORT: 5002
      FAIL: 1
    command: sh -c "node registerService.js & gunicorn -w 4 --threads 2 -b 0.0.0.0:5002 app:app"

  user_management_service_2:
    container_name: user_management_service_2
    build: ./user_management_service
    expose:
      - "5003"
    depends_on:
      - mongodb
      - service_discovery
    environment:
      MONGO_URL: mongodb://mongodb:27017
      SERVICE_NAME: user_management_service
      SERVICE_ADDRESS: user_management_service_2
      PORT: 5003
      FAIL: 1
    command: sh -c "node registerService.js & gunicorn -w 4 --threads 2 -b 0.0.0.0:5002 app:app"

  user_management_service_3:
    container_name: user_management_service_3
    build: ./user_management_service
    expose:
      - "5004"
    depends_on:
      - mongodb
      - service_discovery
    environment:
      MONGO_URL: mongodb://mongodb:27017
      SERVICE_NAME: user_management_service
      SERVICE_ADDRESS: user_management_service_3
      PORT: 5004
      FAIL: 0
    command: sh -c "node registerService.js & gunicorn -w 4 --threads 2 -b 0.0.0.0:5002 app:app"

  game_engine_service_1:
    container_name:  game_engine_service_1
    build: ./game_engine_service
    expose:
      - "5005"
    depends_on:
      - gamesdb
      - service_discovery
    environment:
      MONGO_URL: mongodb://gamesdb:27017
      SERVICE_NAME: game_engine_service
      SERVICE_ADDRESS: game_engine_service_1
      PORT: 5005
      FAIL: 1      
    command: sh -c "node registerService.js & gunicorn -k eventlet --timeout 60 -w 5 -b 0.0.0.0:5003 app:app"

  game_engine_service_2:
    container_name:  game_engine_service_2
    build: ./game_engine_service
    expose:
      - "5006"
    depends_on:
      - gamesdb
      - service_discovery
    environment:
      MONGO_URL: mongodb://gamesdb:27017
      SERVICE_NAME: game_engine_service
      SERVICE_ADDRESS: game_engine_service_2
      PORT: 5006
      FAIL: 1      
    command: sh -c "node registerService.js & gunicorn -k eventlet --timeout 60 -w 5 -b 0.0.0.0:5003 app:app"  

  game_engine_service_3:
    container_name:  game_engine_service_3
    build: ./game_engine_service
    expose:
      - "5006"
    depends_on:
      - gamesdb
      - service_discovery
    environment:
      MONGO_URL: mongodb://gamesdb:27017
      SERVICE_NAME: game_engine_service
      SERVICE_ADDRESS: game_engine_service_3
      PORT: 5006
      FAIL: 1      
    command: sh -c "node registerService.js & gunicorn -k eventlet --timeout 60 -w 5 -b 0.0.0.0:5003 app:app"  

  redis:
    container_name: gateway_cache
    image: redis:alpine
    ports:
      - "6380:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  mongo_data: {}
  gamesdb_data: {}
